<?php
  
  # loom-weaver.php @generated by Loom

  # psr-4 namespace autoloading
  $universalNamespaces = array('Loom' => array('source/Loom/'), 'Loom\\Utils' => array('source/Loom/Utils/'));
  $psr4Autoloader = new Psr4Autoloader();
  foreach ($universalNamespaces as $namespace => $path) {
    $psr4Autoloader->addNamespace($namespace, $path);
  }
  $psr4Autoloader->register();
  
  # classmap autoloading
  $universalClassmap = array('bootstrap.php');
  $classmapWeaver = new ClassmapAutoloader();
  $classmapWeaver->register($universalClassmap);
