<?php
  
  # loom-weaver.php @generated by Loom

use Loom\Autoload\ClassmapAutoloader;

  require "Psr4Autoloader.php";
  require "ClassmapAutoloader.php";

  $registerPsr4 = function ($class) {
      
  };

  $classmapAutoloader = function ($class) {
    $classmapWeaver = new ClassmapAutoloader();
    $classmapWeaver->register($classmap);
  };

  spl_autoload_register($psr4Autoloader);
  spl_autoload_register($classmapAutoloader);