<?php
  
  # loom-weaver.php @generated by Loom

  require "ClassmapAutoloader.php";
  require "Psr4Autoloader.php";
    
  $namespaces = array();
  $classmap = array();

  $registerPsr4 = function ($class) {
      
  };

  $classmapAutoloader = function ($className) {

  };

  spl_autoload_register($psr4Autoloader);
  spl_autoload_register($classmapAutoloader);